services:
  api:
    image: ${DOCKER_USERNAME}/devoops-api:latest
    container_name: minitwit_api
    env_file:
      - .env
    expose:
      - '7070'

    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7070" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  app:
    image: ${DOCKER_USERNAME}/devoops-app:latest
    container_name: minitwit_app
    environment:
      ENDPOINT: "http://172.17.0.1:7070"
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    expose:
      - '3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - '9090' # Host port 9091, container port 9090
    command: --config.file=/etc/prometheus/prometheus.yml

networks:
  main:


volumes:
  grafana_storage: {}
