version: "3.8"

services:
  app:
    build:
      context: ./itu-minitwit
      dockerfile: local/Dockerfile
    container_name: minitwit_app
    ports:
      - "8080:8080"
    environment:
      ENDPOINT: "http://172.17.0.1:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  api:
    build:
      context: ./itu-minitwit-api
      dockerfile: local/Dockerfile
    container_name: minitwit_api
    ports:
      - "9090:9090"
    volumes:
      - ./minitwit.db:/app/minitwit.db
    environment:
      DATABASE: "/app/minitwit.db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/msgs"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
