services:
  api_test:
    build:
      context: ./itu-minitwit-api
      dockerfile: local/Dockerfile
    container_name: minitwit_api_test
    volumes:
      - test_minitwit.db:/app
    environment:
      DATABASE: "/app/test_minitwit.db"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/msgs" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    expose:
      - '9090'

  app_test:
    build:
      context: ./itu-minitwit
      dockerfile: local/Dockerfile
    container_name: minitwit_app_test
    depends_on:
      api_test:
        condition: service_healthy
    environment:
      ENDPOINT: "http://api_test:9090"
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  test_runner:
    build:
      context: ./tests
      dockerfile: local/Dockerfile
    container_name: minitwit_tests
    depends_on:
      api_test:
        condition: service_healthy
      app_test:
        condition: service_healthy
    volumes:
      - test_minitwit.db:/app
    command: [ "/bin/sh", "-c", "pytest --tb=short --maxfail=15" ]

volumes:
  test_minitwit.db:
