version: "3.8"

services:
  app:
    build:
      context: ./itu-minitwit
      dockerfile: Dockerfile
    container_name: minitwit_app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
