services:
  api:
    build:
      context: ./itu-minitwit-api
      dockerfile: local/Dockerfile
    container_name: minitwit_api
    depends_on:
      - logstash
    volumes:
      - ./minitwit.db:/app/minitwit.db
    environment:
      DATABASE: "/app/minitwit.db"
      PORT: ":7070"
    networks:
      - elk
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7070/msgs" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    expose:
      - '7070'
  app:
    build:
      context: ./itu-minitwit
      dockerfile: local/Dockerfile
    container_name: minitwit_app
    environment:
      ENDPOINT: "http://host.docker.internal:7070" #change to "http://172.17.0.1:7070" for linux
    ports:
      - '8080:8080'
    networks:
      - elk
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: 8.12.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped
    expose:
      - '9200' # Main Elasticsearch input

  filebeat:
    extends:
      file: ./filebeat/filebeat-compose.yml
      service: filebeat

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    expose:
      - '3000'

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: 8.12.2
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    restart: unless-stopped
    expose:
      - '5601' # Kibana UI Dashboard

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: 8.12.2
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    restart: unless-stopped
    expose:
      - '5044' # Beats input

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    expose:
      - '9090' # Host port 9191, container port 9090

  # The 'setup' service runs a one-off script which initializes users inside
  # Elasticsearch — such as 'logstash_internal' and 'kibana_system' — with the
  # values of the passwords defined in the '.env' file. It also creates the
  # roles required by some of these users.
  #
  # This task only needs to be performed once, during the *initial* startup of
  # the stack. Any subsequent run will reset the passwords of existing users to
  # the values defined inside the '.env' file, and the built-in roles to their
  # default permissions.
  #
  # By default, it is excluded from the services started by 'docker compose up'
  # due to the non-default profile it belongs to. To run it, either provide the
  # '--profile=setup' CLI flag to Compose commands, or "up" the service by name
  # such as 'docker compose up setup'.
  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: 8.12.2
    depends_on:
      - elasticsearch
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    init: true
    profiles:
      - setup

networks:
  elk:
    driver: bridge
  main:


volumes:
  elasticsearch:
  grafana_storage: {}
