{
 "title": "DevOops",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Follow/Unfollows",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "successful_follows", "legendFormat": "{{Succesful follow}}" },
    { "expr": "successful_unfollows", "legendFormat": "{{Succesful unfollows}}" }
   ]
  },
  {
   "title": "Succesful messages",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "successful_message", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users not found",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Users_not_found", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Succesful requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 16 },
   "targets": [
    { "expr": "successful_request", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unsuccessful request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 16 },
   "targets": [
    { "expr": "unsuccessful_request", "legendFormat": "__auto" }
   ]
  }
 ]
}