FROM python:3

RUN pip install --no-cache-dir pytest==8.1.1 \
 && pip install --no-cache-dir requests==2.31.0

WORKDIR /
COPY refactored_python_tests.py ./

CMD ["pytest", "refactored_python_tests.py"]