# syntax=docker/dockerfile:1

FROM golang:1.23.6

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY ./itu-minitwit-api/go.mod ./itu-minitwit-api/go.sum ./
RUN go mod download && go mod verify
COPY ./itu-minitwit-api/schema.sql ./
COPY ./itu-minitwit-api/latest_processed_sim_action_id.txt ./ 

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY ./itu-minitwit-api/*.go ./

# Build<
RUN CGO_ENABLED=1 GOOS=linux go build -o /minitwit-api

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
# EXPOSE 8000

# Run
CMD ["/minitwit-api"]

# Use 'docker build --tag minitwit .' to build the image
# Use 'docker run --publish 8080:8080 minitwit' to run the container