name: Continuous Integration with Static Analysis

on:
  push:
    branches:
      #- main
      - go_fmt

  # allow manual triggers
  workflow_dispatch:
    manual: true

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use go formatter on project
        run: gofmt -s -w .
    
      - name: Check for gofmt changes
        run: git diff --exit-code #returns 0 if gofmt did not make a change
        continue-on-error: true #allows next step even if 1 or error is returned

      - name: Fail on gofmt changes 
        if: ${{ failure() }}
        run: |     #i cannot see where this echos to?
          echo "gofmt found changes. Please format your code."
          exit 1 

  golangci:
    runs-on: ubuntu-latest
    needs: gofmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0