name: Go Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Start minitwit
        run: |
          cd itu-minitwit-api
          nohup go run . &
          sleep 5  # Wait for the server to start

      - name: Install Python and pytest
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install pytest requests

      - name: Wait for minitwit to be ready
        run: |
          until curl -s http://localhost:9090 > /dev/null; do
            echo "Waiting for server..."
            sleep 2
          done

      - name: Run tests with pytest
        run: | 
          cd itu-minitwit-api
          pytest 

      - name: Stop Go server
        run: pkill -f "go run ."