#if this workflow fails on "Fail on gofmt changes" 
#then run $gofmt -s -w . from DevOops folder, commit and try again.

name: Go Linter

on:
  push:
    branches:
      - go_fmt #not static analysis branch
  pull_request: 

  # allow manual triggers
  workflow_dispatch:
    manual: true

  permissions:
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    # pull-requests: read


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}